const facts = [
  { emoji: "🦒", fact: "Een giraf heeft een tong van wel 50 centimeter lang!" },
  { emoji: "🐘", fact: "Olifanten kunnen muziek horen met hun voeten door de grond te voelen!" },
  { emoji: "🦈", fact: "Een haai heeft soms wel 3.000 tanden tegelijk in zijn bek!" },
  { emoji: "🐧", fact: "Een pinguïn kan wel 25 minuten onder water blijven zonder adem te halen!" },
  { emoji: "🦋", fact: "Een vlinder proeft met zijn voeten!" },
  { emoji: "🐬", fact: "Dolfijnen slapen met één oog open zodat ze gevaar zien aankomen!" },
  { emoji: "🦁", fact: "Een leeuw kan wel 80 kilometer per uur rennen — dat is zo snel als een auto op de snelweg!" },
  { emoji: "🐙", fact: "Een octopus heeft drie harten en blauw bloed!" },
  { emoji: "🦜", fact: "Een papegaai kan wel 100 jaar oud worden!" },
  { emoji: "🐢", fact: "Schildpadden bestaan al langer dan de dinosaurussen — meer dan 200 miljoen jaar!" },
  { emoji: "🦊", fact: "Een vos gebruikt het magneetveld van de aarde om zijn prooi te vinden!" },
  { emoji: "🐋", fact: "Een blauwe vinvis is het grootste dier ooit op aarde — groter dan welke dinosaurus dan ook!" },
  { emoji: "🦩", fact: "Flamingo's zijn eigenlijk wit. Ze worden roze van het eten dat ze eten!" },
  { emoji: "🐝", fact: "Een bij moet 1 miljoen bloemen bezoeken om één potje honing te maken!" },
  { emoji: "🦖", fact: "Een T-rex had kleine armpjes, maar zijn bijtkracht was sterker dan die van een krokodil!" },
  { emoji: "🐌", fact: "Een slak kan 3 jaar slapen zonder wakker te worden!" },
  { emoji: "🦅", fact: "Een arend kan een konijn zien van meer dan 3 kilometer afstand!" },
  { emoji: "🐳", fact: "Walvissen zingen liedjes aan elkaar en die zijn soms meer dan 30 minuten lang!" },
  { emoji: "🐿️", fact: "Een eekhoorn vergeet wel 50% van zijn verstopte noten — zo groeien er nieuwe bomen!" },
  { emoji: "🦝", fact: "Was-beren wassen hun eten altijd voordat ze het opeten!" },
  { emoji: "🐊", fact: "Krokodillen kunnen niet hun tong uitsteken — hij zit vastgeplakt!" },
  { emoji: "🦓", fact: "Elke zebra heeft een uniek strepenpatroon, net als een vingerafdruk!" },
  { emoji: "🐸", fact: "Kikkers drinken niet met hun mond, maar nemen water op via hun huid!" },
  { emoji: "🦔", fact: "Een egel heeft wel 5.000 tot 7.000 stekels op zijn rug!" },
  { emoji: "🐺", fact: "Wolven kunnen een geurtje ruiken dat 2,5 kilometer ver weg is!" },
  { emoji: "🦛", fact: "Een nijlpaard kan niet zwemmen — hij loopt gewoon over de rivierboden!" },
  { emoji: "🐻", fact: "Een ijsbeer heeft zwart vel onder zijn witte vacht — je ziet het alleen niet!" },
  { emoji: "🦎", fact: "Een kameleon verandert van kleur om zijn gevoel te tonen, niet om zich te verstoppen!" },
  { emoji: "🦦", fact: "Otters houden elkaars poten vast als ze slapen zodat ze niet wegdrijven!" },
  { emoji: "🐦", fact: "Kolibries kunnen achterwaarts vliegen — als enige vogel ter wereld!" },
  { emoji: "🦗", fact: "Een krekel zingt door zijn vleugels over elkaar te wrijven!" },
  { emoji: "🐮", fact: "Koeien hebben beste vrienden en worden ongelukkig als die er niet zijn!" },
  { emoji: "🦀", fact: "Een krab loopt zijwaarts, maar kan ook gewoon rechtuit als hij haast heeft!" },
  { emoji: "🐡", fact: "Een kogelvis kan zichzelf opblazen tot meer dan het dubbele van zijn normale grootte!" },
  { emoji: "🦟", fact: "Alleen vrouwelijke muggen bijten mensen — mannetjes drinken alleen plantsap!" },
  { emoji: "🐑", fact: "Schapen kunnen gezichten van andere schapen herkennen en onthouden dat wel 2 jaar!" },
  { emoji: "🦘", fact: "Een babykagaroe is zo klein als een druif als het geboren wordt!" },
  { emoji: "🐐", fact: "Geiten hebben rechthoekige pupillen zodat ze bijna 360 graden om zich heen kunnen kijken!" },
  { emoji: "🦩", fact: "Meeuwen drinken zout zeewater — ze hebben speciale klieren om het zout eruit te halen!" },
  { emoji: "🐇", fact: "Konijnen kunnen niet overgeven, zelfs als ze iets eten dat slecht voor ze is!" },
  { emoji: "🦜", fact: "Kraaien zijn zo slim dat ze gereedschap kunnen maken van takjes!" },
  { emoji: "🐠", fact: "Nemo (de clownvis) kan van geslacht veranderen als er een vrouwtje nodig is!" },
  { emoji: "🦏", fact: "Een neushoornhoorn is eigenlijk gemaakt van haar, net als jouw nagels!" },
  { emoji: "🐩", fact: "Poedels werden vroeger getraind als retrieverhonden om watervogels op te halen!" },
  { emoji: "🦆", fact: "Eenden hebben nooit koude voeten — hun poten voelen geen kou!" },
  { emoji: "🐓", fact: "Kippen dromen als ze slapen, net zoals jij!" },
  { emoji: "🦬", fact: "Een bizon kan 65 kilometer per uur rennen ondanks dat hij meer dan 900 kilo weegt!" },
  { emoji: "🐛", fact: "Een rups lost zichzelf volledig op in zijn cocon en bouwt zichzelf opnieuw op als vlinder!" },
  { emoji: "🦠", fact: "In je lichaam zitten meer bacteriën dan er mensen op de hele wereld zijn!" },
  { emoji: "🐣", fact: "Een kuiken praat al met zijn moeder voordat het uit het ei komt!" },
];

export default facts;
